### ISSUE TITLE
The guildmaster teleports the first time you interact with it

### ISSUE THREAD

**Issue by InteJason** [SaphieNyako/Quest_Giver#13]
Expected Behavior: Upon right clicking, the guildmaster stops and look at you, without teleporting.

**Comment by SaphieNyako** [comment]
The reason this happens is because we replace one entity with another. 
The normal villager would be replaced before setting the location, so it would always take the location of the mouse. 
It also had a offset of 1 so it would always teleport above the mouse. 

When replacing it now it will always have a tiny tell that its replaced, and most of the times you will not notice it. 
The guild master will now recognise the player and will look and the player and stop. 

Uploading this in new version 1.0.1
Please let me know if this is acceptable. 
Otherwise we have to replace the entity when it takes up a profession. 
That would be something maybe Computerizer could do.

**Comment by SaphieNyako** [comment]
Fixed uploading in version 1.0.1
